-- Notifications et alertes (évolution du 29/09/2026).
-- 1. Fréquence « Personnalisée » retirée : les règles ainsi configurées sont supprimées (l'historique de leurs envois est conservé).
DELETE FROM "NotificationRule" WHERE "frequency" = 'CUSTOM';
UPDATE "NotificationRule" SET "everyDays" = NULL WHERE "everyDays" IS NOT NULL;

-- 2. Variables {jalon}, {risque}, {seuil} et {document} retirées des messages.
-- 2a. Textes d'origine (amorçage) : réécrits sans ces variables.
UPDATE "NotificationRule" SET "subject" = 'Jalon en retard · {projet}' WHERE "subject" = 'Jalon en retard · {jalon}';
UPDATE "NotificationRule" SET "body" = 'Jalon en retard · {projet}' WHERE "body" = 'Jalon en retard · {jalon}';
UPDATE "NotificationRule" SET "prompt" = 'Jalon en retard · {projet}' WHERE "prompt" = 'Jalon en retard · {jalon}';
UPDATE "NotificationRule" SET "subject" = 'Un jalon du projet {projet} a dépassé sa date prévue du {date}. Ouvrez le planning pour réviser la trajectoire.' WHERE "subject" = 'Le jalon {jalon} du projet {projet} a dépassé sa date prévue du {date}. Ouvrez le planning pour réviser la trajectoire.';
UPDATE "NotificationRule" SET "body" = 'Un jalon du projet {projet} a dépassé sa date prévue du {date}. Ouvrez le planning pour réviser la trajectoire.' WHERE "body" = 'Le jalon {jalon} du projet {projet} a dépassé sa date prévue du {date}. Ouvrez le planning pour réviser la trajectoire.';
UPDATE "NotificationRule" SET "prompt" = 'Un jalon du projet {projet} a dépassé sa date prévue du {date}. Ouvrez le planning pour réviser la trajectoire.' WHERE "prompt" = 'Le jalon {jalon} du projet {projet} a dépassé sa date prévue du {date}. Ouvrez le planning pour réviser la trajectoire.';
UPDATE "NotificationRule" SET "subject" = 'Tu es l’assistant PMO du projet {projet}. Un jalon a dépassé sa date prévue du {date}. Rédige une alerte de 3 phrases maximum : le constat, l’impact probable sur le planning et l’action attendue du responsable. Ton factuel, sans formule de politesse.' WHERE "subject" = 'Tu es l’assistant PMO du projet {projet}. Le jalon {jalon} a dépassé sa date prévue du {date}. Rédige une alerte de 3 phrases maximum : le constat, l’impact probable sur le planning et l’action attendue du responsable. Ton factuel, sans formule de politesse.';
UPDATE "NotificationRule" SET "body" = 'Tu es l’assistant PMO du projet {projet}. Un jalon a dépassé sa date prévue du {date}. Rédige une alerte de 3 phrases maximum : le constat, l’impact probable sur le planning et l’action attendue du responsable. Ton factuel, sans formule de politesse.' WHERE "body" = 'Tu es l’assistant PMO du projet {projet}. Le jalon {jalon} a dépassé sa date prévue du {date}. Rédige une alerte de 3 phrases maximum : le constat, l’impact probable sur le planning et l’action attendue du responsable. Ton factuel, sans formule de politesse.';
UPDATE "NotificationRule" SET "prompt" = 'Tu es l’assistant PMO du projet {projet}. Un jalon a dépassé sa date prévue du {date}. Rédige une alerte de 3 phrases maximum : le constat, l’impact probable sur le planning et l’action attendue du responsable. Ton factuel, sans formule de politesse.' WHERE "prompt" = 'Tu es l’assistant PMO du projet {projet}. Le jalon {jalon} a dépassé sa date prévue du {date}. Rédige une alerte de 3 phrases maximum : le constat, l’impact probable sur le planning et l’action attendue du responsable. Ton factuel, sans formule de politesse.';
UPDATE "NotificationRule" SET "subject" = 'Un risque est devenu critique (probabilité × impact ≥ 20) sur {projet}. Un plan de traitement est attendu.' WHERE "subject" = 'Le risque « {risque} » est devenu critique (probabilité × impact ≥ 20) sur {projet}. Un plan de traitement est attendu.';
UPDATE "NotificationRule" SET "body" = 'Un risque est devenu critique (probabilité × impact ≥ 20) sur {projet}. Un plan de traitement est attendu.' WHERE "body" = 'Le risque « {risque} » est devenu critique (probabilité × impact ≥ 20) sur {projet}. Un plan de traitement est attendu.';
UPDATE "NotificationRule" SET "prompt" = 'Un risque est devenu critique (probabilité × impact ≥ 20) sur {projet}. Un plan de traitement est attendu.' WHERE "prompt" = 'Le risque « {risque} » est devenu critique (probabilité × impact ≥ 20) sur {projet}. Un plan de traitement est attendu.';
UPDATE "NotificationRule" SET "subject" = 'Tu es l’assistant PMO du projet {projet}. Un risque est devenu critique. Résume en 2 phrases pourquoi, puis propose une première action de traitement. Ne cite que des faits présents dans les données du projet.' WHERE "subject" = 'Tu es l’assistant PMO du projet {projet}. Le risque « {risque} » est devenu critique. Résume en 2 phrases pourquoi, puis propose une première action de traitement. Ne cite que des faits présents dans les données du projet.';
UPDATE "NotificationRule" SET "body" = 'Tu es l’assistant PMO du projet {projet}. Un risque est devenu critique. Résume en 2 phrases pourquoi, puis propose une première action de traitement. Ne cite que des faits présents dans les données du projet.' WHERE "body" = 'Tu es l’assistant PMO du projet {projet}. Le risque « {risque} » est devenu critique. Résume en 2 phrases pourquoi, puis propose une première action de traitement. Ne cite que des faits présents dans les données du projet.';
UPDATE "NotificationRule" SET "prompt" = 'Tu es l’assistant PMO du projet {projet}. Un risque est devenu critique. Résume en 2 phrases pourquoi, puis propose une première action de traitement. Ne cite que des faits présents dans les données du projet.' WHERE "prompt" = 'Tu es l’assistant PMO du projet {projet}. Le risque « {risque} » est devenu critique. Résume en 2 phrases pourquoi, puis propose une première action de traitement. Ne cite que des faits présents dans les données du projet.';
UPDATE "NotificationRule" SET "subject" = 'Budget IA : seuil d’alerte atteint' WHERE "subject" = 'Budget IA : seuil de {seuil} atteint';
UPDATE "NotificationRule" SET "body" = 'Budget IA : seuil d’alerte atteint' WHERE "body" = 'Budget IA : seuil de {seuil} atteint';
UPDATE "NotificationRule" SET "prompt" = 'Budget IA : seuil d’alerte atteint' WHERE "prompt" = 'Budget IA : seuil de {seuil} atteint';
UPDATE "NotificationRule" SET "subject" = 'La consommation IA du mois a atteint le seuil d’alerte du plafond fixé. Consultez la console pour ajuster les modèles ou le budget.' WHERE "subject" = 'La consommation IA du mois atteint {seuil} du plafond fixé. Consultez la console pour ajuster les modèles ou le budget.';
UPDATE "NotificationRule" SET "body" = 'La consommation IA du mois a atteint le seuil d’alerte du plafond fixé. Consultez la console pour ajuster les modèles ou le budget.' WHERE "body" = 'La consommation IA du mois atteint {seuil} du plafond fixé. Consultez la console pour ajuster les modèles ou le budget.';
UPDATE "NotificationRule" SET "prompt" = 'La consommation IA du mois a atteint le seuil d’alerte du plafond fixé. Consultez la console pour ajuster les modèles ou le budget.' WHERE "prompt" = 'La consommation IA du mois atteint {seuil} du plafond fixé. Consultez la console pour ajuster les modèles ou le budget.';
UPDATE "NotificationRule" SET "subject" = 'Rédige une alerte courte pour l’administrateur : la consommation IA du mois a atteint le seuil d’alerte du plafond. Indique la fonction qui consomme le plus et un levier d’économie chiffré.' WHERE "subject" = 'Rédige une alerte courte pour l’administrateur : la consommation IA du mois atteint {seuil} du plafond. Indique la fonction qui consomme le plus et un levier d’économie chiffré.';
UPDATE "NotificationRule" SET "body" = 'Rédige une alerte courte pour l’administrateur : la consommation IA du mois a atteint le seuil d’alerte du plafond. Indique la fonction qui consomme le plus et un levier d’économie chiffré.' WHERE "body" = 'Rédige une alerte courte pour l’administrateur : la consommation IA du mois atteint {seuil} du plafond. Indique la fonction qui consomme le plus et un levier d’économie chiffré.';
UPDATE "NotificationRule" SET "prompt" = 'Rédige une alerte courte pour l’administrateur : la consommation IA du mois a atteint le seuil d’alerte du plafond. Indique la fonction qui consomme le plus et un levier d’économie chiffré.' WHERE "prompt" = 'Rédige une alerte courte pour l’administrateur : la consommation IA du mois atteint {seuil} du plafond. Indique la fonction qui consomme le plus et un levier d’économie chiffré.';
UPDATE "NotificationRule" SET "subject" = 'Document analysé · {projet}' WHERE "subject" = 'Document analysé · {document}';
UPDATE "NotificationRule" SET "body" = 'Document analysé · {projet}' WHERE "body" = 'Document analysé · {document}';
UPDATE "NotificationRule" SET "prompt" = 'Document analysé · {projet}' WHERE "prompt" = 'Document analysé · {document}';
UPDATE "NotificationRule" SET "subject" = 'Jev a extrait les décisions et actions d’un nouveau document de {projet}. Vérifiez les éléments proposés avant intégration.' WHERE "subject" = 'Jev a extrait les décisions et actions de {document}. Vérifiez les éléments proposés avant intégration.';
UPDATE "NotificationRule" SET "body" = 'Jev a extrait les décisions et actions d’un nouveau document de {projet}. Vérifiez les éléments proposés avant intégration.' WHERE "body" = 'Jev a extrait les décisions et actions de {document}. Vérifiez les éléments proposés avant intégration.';
UPDATE "NotificationRule" SET "prompt" = 'Jev a extrait les décisions et actions d’un nouveau document de {projet}. Vérifiez les éléments proposés avant intégration.' WHERE "prompt" = 'Jev a extrait les décisions et actions de {document}. Vérifiez les éléments proposés avant intégration.';
UPDATE "NotificationRule" SET "subject" = 'Un nouveau document de {projet} vient d’être analysé. Liste en puces les décisions, actions et risques extraits, chacun avec sa page source. Termine par : « À vérifier avant intégration ».' WHERE "subject" = 'Le document {document} vient d’être analysé. Liste en puces les décisions, actions et risques extraits, chacun avec sa page source. Termine par : « À vérifier avant intégration ».';
UPDATE "NotificationRule" SET "body" = 'Un nouveau document de {projet} vient d’être analysé. Liste en puces les décisions, actions et risques extraits, chacun avec sa page source. Termine par : « À vérifier avant intégration ».' WHERE "body" = 'Le document {document} vient d’être analysé. Liste en puces les décisions, actions et risques extraits, chacun avec sa page source. Termine par : « À vérifier avant intégration ».';
UPDATE "NotificationRule" SET "prompt" = 'Un nouveau document de {projet} vient d’être analysé. Liste en puces les décisions, actions et risques extraits, chacun avec sa page source. Termine par : « À vérifier avant intégration ».' WHERE "prompt" = 'Le document {document} vient d’être analysé. Liste en puces les décisions, actions et risques extraits, chacun avec sa page source. Termine par : « À vérifier avant intégration ».';

-- 2b. Tout autre texte : retrait automatique de la variable (et des guillemets ou de la ponctuation laissés orphelins).
CREATE OR REPLACE FUNCTION pg_temp.sans_variables_retirees(t text) RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT btrim(regexp_replace(regexp_replace(regexp_replace(regexp_replace(
    regexp_replace(t, '[[:space:]  ]*«[[:space:]  ]*\{(jalon|risque|seuil|document)\}[[:space:]  ]*»', '', 'g'),
    '[[:space:]  ]*\{(jalon|risque|seuil|document)\}', '', 'g'),
    '[[:space:]  ]+:[[:space:]]*([.,])', '\1', 'g'),
    '[[:space:]  ]*[·:,][[:space:]  ]*$', '', 'g'),
    '[[:space:]]{2,}', ' ', 'g'))
$$;
UPDATE "NotificationRule" SET
  "subject" = pg_temp.sans_variables_retirees("subject"),
  "body" = pg_temp.sans_variables_retirees("body"),
  "prompt" = pg_temp.sans_variables_retirees("prompt")
WHERE "subject" ~ '\{(jalon|risque|seuil|document)\}' OR "body" ~ '\{(jalon|risque|seuil|document)\}' OR "prompt" ~ '\{(jalon|risque|seuil|document)\}';

-- 3. Heures d'envoi alignées sur le pas de 30 minutes.
UPDATE "NotificationRule" SET "hour" = substr("hour", 1, 3) || CASE WHEN substr("hour", 4, 2)::int < 30 THEN '00' ELSE '30' END
WHERE "hour" ~ '^[0-2][0-9]:[0-5][0-9]$' AND substr("hour", 4, 2) NOT IN ('00', '30');
