/**
 * Dictionnaire des données du Cockpit (interrogation en langage naturel, Text-to-SQL) : une fiche par vue du
 * schéma `jev_cockpit`, sur le modèle du dictionnaire de la Console (`jev-dictionnaire.ts`, mêmes types).
 *
 * Périmètre : ce que le Cockpit lit et affiche, projet par projet. Exclus : chemins de stockage, images, JSON de
 * présentation (ContentBlock — sauf l'objet « Info projet », vue infos_projet —, ProjectSection, fiche d'arbitrage, composants de template), tâches privées (Task,
 * TaskOverride), tables de la Console et de l'authentification.
 * Droits (RG5 / RG8) : chaque vue porte `projet_id`, et `chantier_id` quand l'objet appartient à un chantier ; la règle
 * de lecture est écrite dans chaque fiche. Seul le rôle `jev_lecteur_cockpit` peut les lire, et il ne voit que le
 * périmètre posé par le serveur pour la requête (`rise.projet`, `rise.chantiers`) : voir `cockpitViewSql()`.
 * Dates : les dates métier sont du texte AAAA-MM-JJ ; les horodatages sont convertis en heure de Paris.
 */
import { DictTable, P, q } from './jev-dictionnaire';

export const JEV_COCKPIT_SCHEMA = 'jev_cockpit';
/** Rôle de lecture des vues du Cockpit (rédaction des notifications) ; distinct de celui du Jev de la Console. */
export const JEV_COCKPIT_ROLE = 'jev_lecteur_cockpit';
/** Paramètres de session posés par le serveur avant chaque requête : projet, et chantiers lisibles (« * » : tous). */
export const SCOPE_PROJET = 'rise.projet';
export const SCOPE_CHANTIERS = 'rise.chantiers';

const DROITS_PROJET = 'Droits : visible de tout utilisateur habilité sur le projet (projet_id).';
const DROITS_CHANTIER = 'Droits : le PMO voit tout le projet ; un Responsable ou un Lecteur ne voit que les lignes dont chantier_id fait partie de ses chantiers (habilitations).';
const DATES_TEXTE = 'Les dates sont du texte AAAA-MM-JJ : comparer comme du texte, ou convertir avec ::date pour calculer un écart en jours.';
const PLAN = 'PLANNED = prévue, IN_PROGRESS = en cours, DONE = terminée';
const PREC = 'D = jour (JJ/MM/AAAA), M = mois (MM/AAAA), Y = année (AAAA) ; en M ou Y, la date stockée est le 1er jour (début) ou le dernier jour (fin)';
const AVANCEMENT_PREVU = 'Avancement prévu = avancement_prevu_force_pct s’il est renseigné ; sinon 0 si une date manque ; sinon round(clamp((date du jour − date_debut) / max(1, date_fin − date_debut), 0, 1) × 100). Avancement réel = avancement_reel_pct.';
const EN_COURS = 'En cours = date_debut ≤ date du jour ≤ date_fin (les deux dates renseignées).';

export const DICTIONNAIRE_COCKPIT: DictTable[] = [
  // ───────────── Projet et référentiel ─────────────
  {
    nom: 'projets',
    source: '"Project" t LEFT JOIN "Client" c ON c.id = t."clientId"',
    description: 'Projets pilotés dans le Cockpit : identité, client, dates, statut, date de mise en service (Go-Live) prévue, appréciation manuelle de santé. Écrans : Info projet, Aujourd’hui, Pilotage.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du projet (= projet_id des autres vues)' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code du projet', exemples: 'RISE' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom du projet' },
      { nom: 'client', expr: 'c.name', type: 'texte', signification: 'Nom du client' },
      { nom: 'objectif', expr: 't.objective', type: 'texte', signification: 'Objectif du projet' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'PREPARATION = préparation, ACTIVE = actif, CLOSED = clos' },
      { nom: 'date_debut', expr: `t.${q('startDate')}`, type: 'texte', signification: 'Date de début', exemples: 'AAAA-MM-JJ' },
      { nom: 'date_fin_cible', expr: `t.${q('targetEndDate')}`, type: 'texte', signification: 'Date de fin visée', exemples: 'AAAA-MM-JJ' },
      { nom: 'date_golive_prevue', expr: `t.${q('forecastGoliveIso')}`, type: 'texte', signification: 'Date de mise en service (Go-Live) prévue', exemples: 'AAAA-MM-JJ' },
      { nom: 'directeur_programme_id', expr: `t.${q('programDirectorId')}`, type: 'texte', signification: 'Directeur de programme → personnes.id' },
      { nom: 'sponsor_id', expr: `t.${q('sponsorId')}`, type: 'texte', signification: 'Sponsor → personnes.id' },
      { nom: 'equipe_editeur_id', expr: `t.${q('editorTeamId')}`, type: 'texte', signification: 'Équipe de l’éditeur → equipes.id' },
      { nom: 'equipe_integrateur_id', expr: `t.${q('integratorTeamId')}`, type: 'texte', signification: 'Équipe de l’intégrateur → equipes.id' },
      { nom: 'ville', expr: 't.city', type: 'texte', signification: 'Ville' },
      { nom: 'pays', expr: 't.country', type: 'texte', signification: 'Pays' },
      { nom: 'devise', expr: 't.currency', type: 'texte', signification: 'Devise des montants', exemples: 'EUR' },
      { nom: 'fuseau', expr: 't.timezone', type: 'texte', signification: 'Fuseau horaire du projet (date du jour)', exemples: 'Europe/Paris' },
      { nom: 'sante_manuelle', expr: `t.${q('healthOverride')}->>'value'`, type: 'texte', signification: 'Appréciation manuelle de la santé du projet (null si aucune)' },
      { nom: 'sante_motif', expr: `t.${q('healthOverride')}->>'reason'`, type: 'texte', signification: 'Motif de l’appréciation manuelle' },
    ],
    relations: ['projets.id = projet_id de toutes les autres vues', 'projets.directeur_programme_id, sponsor_id = personnes.id', 'projets.equipe_editeur_id, equipe_integrateur_id = equipes.id'],
    usages: ['Quand est le Go-Live ? Combien de jours restent ?', 'Quel est le statut, le client, l’objectif du projet ?'],
    regles: [
      'Compte à rebours du Go-Live = date_golive_prevue::date − date du jour (J-n ; J+n si dépassée) ; à défaut, la date du jalon de Go-Live (jalons).',
      'Fin de projet affichée = la plus grande date_fin des phases, sinon date_fin_cible.',
      'Aucune météo n’est calculée : la santé affichée est seulement l’appréciation manuelle (sante_manuelle).',
      DATES_TEXTE,
      DROITS_PROJET + ' Le directeur de programme a accès au projet.',
    ],
  },
  {
    nom: 'infos_projet',
    // Objet « Info projet » (30/09/2026) : rubriques du bloc `referential` (ContentBlock), une ligne par élément.
    source: `(SELECT b.${q('projectId')} AS project_id, r.rubrique, r.ordre_rubrique, e.ord AS ordre,
      CASE WHEN r.kv THEN e.el->>0 END AS libelle, CASE WHEN r.kv THEN e.el->>1 ELSE e.el#>>'{}' END AS valeur
    FROM ${q('ContentBlock')} b
    CROSS JOIN LATERAL (VALUES ('Le client', 1, 'identity', true), ('Marques du groupe', 2, 'brands', false), ('Programme en une phrase', 3, 'pitch', false), ('Enjeux stratégiques', 4, 'stakes', false),
      ('Périmètre fonctionnel', 5, 'scope', true), ('Périmètre applicatif', 6, 'systems', true), ('Périmètre géographique', 7, 'geo', false), ('Périmètre juridique', 8, 'legal', false)) r(rubrique, ordre_rubrique, cle, kv)
    CROSS JOIN LATERAL jsonb_array_elements(CASE jsonb_typeof(b.data::jsonb -> r.cle) WHEN 'array' THEN b.data::jsonb -> r.cle WHEN 'string' THEN jsonb_build_array(b.data::jsonb -> r.cle) ELSE '[]'::jsonb END) WITH ORDINALITY e(el, ord)
    WHERE b.key = 'referential' AND coalesce(CASE WHEN r.kv THEN e.el->>1 ELSE e.el#>>'{}' END, '') <> '') t`,
    description: 'Objet « Info projet » du Référentiel : contexte client et périmètre du projet (client, marques du groupe, programme en une phrase, enjeux stratégiques, périmètres fonctionnel, applicatif, géographique et juridique), une ligne par élément. Écrans : Info projet › Fiche projet, Référentiel › Info projet.',
    colonnes: [
      { nom: 'id', expr: `t.project_id || ':' || t.ordre_rubrique || ':' || t.ordre`, type: 'texte', signification: 'Identifiant de la ligne (projet:rubrique:rang)' },
      { nom: 'projet_id', expr: 't.project_id', type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'rubrique', expr: 't.rubrique', type: 'texte', signification: 'Rubrique de l’objet', exemples: 'Le client, Marques du groupe, Programme en une phrase, Enjeux stratégiques, Périmètre fonctionnel, Périmètre applicatif, Périmètre géographique, Périmètre juridique' },
      { nom: 'ordre_rubrique', expr: 't.ordre_rubrique', type: 'entier', signification: 'Rang de la rubrique (1 à 8, ordre ci-dessus)' },
      { nom: 'ordre', expr: 't.ordre', type: 'entier', signification: 'Rang de l’élément dans sa rubrique (à partir de 1)' },
      { nom: 'libelle', expr: 't.libelle', type: 'texte', signification: 'Libellé (Le client, périmètres fonctionnel et applicatif) ; null pour les rubriques en liste', exemples: 'Raison sociale, Siège, Finance' },
      { nom: 'valeur', expr: 't.valeur', type: 'texte', signification: 'Valeur de l’élément (texte, marque, enjeu, pays, entité…)' },
    ],
    relations: ['infos_projet.projet_id = projets.id'],
    usages: ['Quels sont les enjeux stratégiques du projet ?', 'Quel est le périmètre géographique (pays) ou juridique (entités) ?', 'Quelles marques du groupe sont concernées ?'],
    regles: [
      'Ordre d’affichage = ordre_rubrique puis ordre. Nombre de pays = nombre de lignes de la rubrique « Périmètre géographique » ; nombre d’entités = celles de « Périmètre juridique ».',
      'Le programme en une phrase est une seule ligne ; les rubriques en liste n’ont pas de libellé.',
      DROITS_PROJET,
    ],
  },
  {
    nom: 'references_planning',
    source: '"BaselineVersion" t',
    description: 'Versions de la référence de planning (baseline) d’un projet : version, date de Go-Live de référence, approbation. Une seule est en vigueur.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'version', expr: 't.version', type: 'texte', signification: 'Version', exemples: 'v4, v5' },
      { nom: 'date', expr: 't.date', type: 'texte', signification: 'Date de référence de la version', exemples: 'AAAA-MM-JJ' },
      { nom: 'approuvee_le', expr: `t.${q('approvedAt')}`, type: 'texte', signification: 'Date d’approbation', exemples: 'AAAA-MM-JJ' },
      { nom: 'approuvee_par_id', expr: `t.${q('approvedById')}`, type: 'texte', signification: 'Approbateur → personnes.id' },
      { nom: 'motif', expr: 't.reason', type: 'texte', signification: 'Motif du changement de référence' },
      { nom: 'en_vigueur', expr: 't.current', type: 'booléen', signification: 'Version en vigueur' },
    ],
    relations: ['references_planning.projet_id = projets.id'],
    usages: ['Quelle est la référence de planning en vigueur, et la précédente ?'],
    regles: ['Référence en vigueur = en_vigueur vrai ; la précédente = la plus récente des autres.', DATES_TEXTE, DROITS_PROJET],
  },
  {
    nom: 'lots',
    source: '"Wave" t',
    description: 'Lots (vagues de déploiement) d’un projet, avec leurs dates et leur statut.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du lot' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'numero', expr: 't.seq', type: 'entier', signification: 'Numéro du lot (affiché « Lot n »)' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom du lot' },
      { nom: 'date_debut', expr: `t.${q('startDate')}`, type: 'texte', signification: 'Date de début', exemples: 'AAAA-MM-JJ' },
      { nom: 'date_fin', expr: `t.${q('endDate')}`, type: 'texte', signification: 'Date de fin', exemples: 'AAAA-MM-JJ' },
      { nom: 'precision_debut', expr: `t.${q('startPrec')}::text`, type: 'texte', signification: 'Précision de la date de début', exemples: PREC },
      { nom: 'precision_fin', expr: `t.${q('endPrec')}::text`, type: 'texte', signification: 'Précision de la date de fin', exemples: 'D, M, Y' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'PLANNED = prévu, IN_PROGRESS = en cours, DONE = terminé' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Responsable → personnes.id' },
    ],
    relations: ['lots.projet_id = projets.id', 'lots.id = jalons.lot_id, chantiers_lots.lot_id'],
    usages: ['Quels sont les lots et leurs dates ?', 'Quel lot est en cours ?'],
    regles: [EN_COURS, DATES_TEXTE, DROITS_PROJET],
  },
  {
    nom: 'phases',
    source: '"Phase" t',
    description: 'Phases du planning d’un projet : dates, statut, avancement réel et prévu, criticité. Écrans : Pilotage › Planning.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant de la phase' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'ordre', expr: 't.seq', type: 'entier', signification: 'Rang de la phase' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code', exemples: '1, 2, 5' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom de la phase' },
      { nom: 'description', expr: 't.description', type: 'texte', signification: 'Description' },
      { nom: 'date_debut', expr: `t.${q('startDate')}`, type: 'texte', signification: 'Début (toujours renseigné)', exemples: 'AAAA-MM-JJ' },
      { nom: 'date_fin', expr: `t.${q('endDate')}`, type: 'texte', signification: 'Fin (toujours renseignée)', exemples: 'AAAA-MM-JJ' },
      { nom: 'precision_debut', expr: `t.${q('startPrec')}::text`, type: 'texte', signification: 'Précision de la date de début', exemples: PREC },
      { nom: 'precision_fin', expr: `t.${q('endPrec')}::text`, type: 'texte', signification: 'Précision de la date de fin', exemples: 'D, M, Y' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: PLAN },
      { nom: 'avancement_reel_pct', expr: `t.${q('progressPct')}`, type: 'entier', signification: 'Avancement réel', exemples: 'en %' },
      { nom: 'avancement_prevu_force_pct', expr: `t.${q('plannedPctOverride')}`, type: 'entier', signification: 'Avancement prévu saisi à la main (null : calculé)', exemples: 'en %' },
      { nom: 'critique', expr: 't.critical', type: 'booléen', signification: 'Sur le chemin critique' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Responsable → personnes.id' },
    ],
    relations: ['phases.projet_id = projets.id', 'phases.id = sous_phases.phase_id, jalons.phase_id, chantiers_phases.phase_id'],
    usages: ['Quelle phase est en cours ?', 'Quelles phases sont en retard sur leur avancement prévu ?', 'Chemin critique.'],
    regles: [AVANCEMENT_PREVU, EN_COURS, 'Retard d’avancement = avancement prévu − avancement réel > 0.', DATES_TEXTE, DROITS_PROJET],
  },
  {
    nom: 'sous_phases',
    source: '"Subphase" t',
    description: 'Sous-phases d’une phase (code « phase.n ») : dates, statut, avancement, criticité.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant de la sous-phase' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'phase_id', expr: `t.${q('phaseId')}`, type: 'texte', signification: 'Phase → phases.id' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code', exemples: '5.2, 5.3' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom de la sous-phase' },
      { nom: 'description', expr: 't.description', type: 'texte', signification: 'Description' },
      { nom: 'date_debut', expr: `t.${q('startDate')}`, type: 'texte', signification: 'Début (null possible)', exemples: 'AAAA-MM-JJ' },
      { nom: 'date_fin', expr: `t.${q('endDate')}`, type: 'texte', signification: 'Fin (null possible)', exemples: 'AAAA-MM-JJ' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: PLAN },
      { nom: 'avancement_reel_pct', expr: `t.${q('progressPct')}`, type: 'entier', signification: 'Avancement réel', exemples: 'en %' },
      { nom: 'avancement_prevu_force_pct', expr: `t.${q('plannedPctOverride')}`, type: 'entier', signification: 'Avancement prévu saisi à la main', exemples: 'en %' },
      { nom: 'critique', expr: 't.critical', type: 'booléen', signification: 'Sur le chemin critique' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Responsable → personnes.id' },
    ],
    relations: ['sous_phases.phase_id = phases.id', 'sous_phases.id = livrables.sous_phase_id, jalons.sous_phase_id'],
    usages: ['Chemin critique détaillé.', 'Sous-phases en cours.'],
    regles: [AVANCEMENT_PREVU, EN_COURS, DATES_TEXTE, DROITS_PROJET],
  },
  {
    nom: 'chantiers',
    source: '"Workstream" t',
    description: 'Chantiers (workstreams) d’un projet : responsable, dates, avancement. Le chantier est l’unité des droits des Responsables et des Lecteurs.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du chantier (= chantier_id des autres vues)' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code', exemples: 'C1 … C8 (C8 porte le baromètre)' },
      { nom: 'ordre', expr: 't.seq', type: 'entier', signification: 'Rang' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom du chantier' },
      { nom: 'description', expr: 't.description', type: 'texte', signification: 'Description' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Responsable → personnes.id' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'ACTIVE = actif, CLOSED = clos' },
      { nom: 'date_debut', expr: `t.${q('startDate')}`, type: 'texte', signification: 'Date de début', exemples: 'AAAA-MM-JJ' },
      { nom: 'date_fin', expr: `t.${q('endDate')}`, type: 'texte', signification: 'Date de fin', exemples: 'AAAA-MM-JJ' },
      { nom: 'avancement_reel_pct', expr: `t.${q('progressPct')}`, type: 'entier', signification: 'Avancement réel', exemples: 'en %' },
      { nom: 'avancement_prevu_force_pct', expr: `t.${q('plannedPctOverride')}`, type: 'entier', signification: 'Avancement prévu saisi à la main', exemples: 'en %' },
      { nom: 'critique', expr: 't.critical', type: 'booléen', signification: 'Chantier critique' },
      { nom: 'depend_de_tous', expr: `t.${q('dependsOnAll')}`, type: 'booléen', signification: 'Dépend de tous les autres chantiers (« Tous »)' },
    ],
    relations: ['chantiers.projet_id = projets.id', 'chantiers.id = chantier_id des vues risques, problemes, actions, decisions, avancements, jalons, livrables, habilitations'],
    usages: ['Qui est responsable de quel chantier ?', 'Chantiers en retard d’avancement.'],
    regles: [AVANCEMENT_PREVU, DATES_TEXTE, 'Droits : le Cockpit affiche la liste de tous les chantiers du projet ; leur contenu (risques, actions…) est filtré par chantier.'],
  },
  {
    nom: 'chantiers_phases',
    source: '"WorkstreamPhase" t JOIN "Workstream" w ON w.id = t."wsId"',
    description: 'Phases couvertes par chaque chantier.',
    colonnes: [
      { nom: 'projet_id', expr: 'w."projectId"', type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier → chantiers.id' },
      { nom: 'phase_id', expr: `t.${q('phaseId')}`, type: 'texte', signification: 'Phase → phases.id' },
    ],
    relations: ['chantiers_phases.chantier_id = chantiers.id', 'chantiers_phases.phase_id = phases.id'],
    usages: ['Quels chantiers travaillent sur telle phase ?'],
    regles: [DROITS_PROJET],
  },
  {
    nom: 'chantiers_lots',
    source: '"WorkstreamWave" t JOIN "Workstream" w ON w.id = t."wsId"',
    description: 'Lots concernés par chaque chantier.',
    colonnes: [
      { nom: 'projet_id', expr: 'w."projectId"', type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier → chantiers.id' },
      { nom: 'lot_id', expr: `t.${q('waveId')}`, type: 'texte', signification: 'Lot → lots.id' },
    ],
    relations: ['chantiers_lots.chantier_id = chantiers.id', 'chantiers_lots.lot_id = lots.id'],
    usages: ['Quels chantiers participent à tel lot ?'],
    regles: [DROITS_PROJET],
  },
  {
    nom: 'dependances_chantiers',
    source: '"WorkstreamDependency" t JOIN "Workstream" w ON w.id = t."wsId"',
    description: 'Dépendances entre chantiers : le chantier dépend d’un autre chantier.',
    colonnes: [
      { nom: 'projet_id', expr: 'w."projectId"', type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier dépendant → chantiers.id' },
      { nom: 'depend_de_id', expr: `t.${q('dependsOnId')}`, type: 'texte', signification: 'Chantier dont il dépend → chantiers.id' },
    ],
    relations: ['dependances_chantiers.chantier_id, depend_de_id = chantiers.id'],
    usages: ['De quels chantiers dépend tel chantier ?'],
    regles: ['Un chantier avec depend_de_tous (chantiers) dépend de tous les autres, sans ligne ici.', DROITS_PROJET],
  },
  {
    nom: 'avancements',
    source: '"WorkstreamProgress" t',
    description: 'Bloc « Avancement » par chantier : valeur réelle et cible en %, avec son signal (en bonne voie, vigilance, en risque). Écrans : Aujourd’hui, Pilotage.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier → chantiers.id' },
      { nom: 'libelle', expr: 't.label', type: 'texte', signification: 'Libellé de l’indicateur' },
      { nom: 'reel_pct', expr: `t.${q('valuePct')}`, type: 'entier', signification: 'Valeur réelle', exemples: 'en %' },
      { nom: 'cible_pct', expr: `t.${q('targetPct')}`, type: 'entier', signification: 'Valeur cible', exemples: 'en %' },
      { nom: 'detail', expr: 't.detail', type: 'texte', signification: 'Commentaire' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Responsable → personnes.id' },
      { nom: 'confirme_le', expr: P(q('confirmedAt')), type: 'date-heure', signification: 'Dernière confirmation de la valeur (heure de Paris)' },
    ],
    relations: ['avancements.chantier_id = chantiers.id'],
    usages: ['Quels chantiers sont en risque sur leur avancement ?'],
    regles: [
      'Signal : écart = reel_pct − cible_pct ; RISK (en risque) si écart < −20 ; WATCH (vigilance) si écart < 0 ; OK (en bonne voie) sinon.',
      'Fraîcheur : ALERT si la dernière confirmation date de plus de 14 jours, WATCH si plus de 7 jours, OK sinon.',
      DROITS_CHANTIER,
    ],
  },
  {
    nom: 'jalons',
    source: '"Milestone" t',
    description: 'Jalons du planning : date prévue, date de référence, confirmation. Écrans : Pilotage › Jalons, Aujourd’hui (échéancier).',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du jalon', exemples: 'J08' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code', exemples: 'J01 … J08' },
      { nom: 'libelle', expr: 't.n', type: 'texte', signification: 'Libellé', exemples: 'Go-Live Lot 1' },
      { nom: 'phase_id', expr: `t.${q('phaseId')}`, type: 'texte', signification: 'Phase → phases.id' },
      { nom: 'sous_phase_id', expr: `t.${q('subphaseId')}`, type: 'texte', signification: 'Sous-phase → sous_phases.id' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier → chantiers.id (null : jalon de projet)' },
      { nom: 'lot_id', expr: `t.${q('waveId')}`, type: 'texte', signification: 'Lot → lots.id' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Responsable → personnes.id' },
      { nom: 'date_prevue', expr: 't.iso', type: 'texte', signification: 'Date prévue actuelle', exemples: 'AAAA-MM-JJ' },
      { nom: 'date_reference', expr: `t.${q('baselineIso')}`, type: 'texte', signification: 'Date de la référence de planning', exemples: 'AAAA-MM-JJ' },
      { nom: 'confirme_le', expr: P(q('confirmedAt')), type: 'date-heure', signification: 'Dernière confirmation de la date (heure de Paris ; null : jamais)' },
    ],
    relations: ['jalons.phase_id = phases.id', 'jalons.chantier_id = chantiers.id', 'jalons.lot_id = lots.id'],
    usages: ['Prochains jalons.', 'Jalons en glissement par rapport à la référence.', 'Jalons non confirmés.'],
    regles: [
      'Écart à la référence (jours) = date_prevue::date − date_reference::date ; 0 = conforme ; positif = glissement.',
      'État : passé si date_prevue < date du jour ; « prochain » = le premier jalon (trié par date_prevue puis code) avec date_prevue ≥ date du jour ; à venir pour les suivants.',
      'Jours depuis la confirmation = date du jour − date de confirme_le (0 si jamais confirmé). Anomalie « jalon non confirmé » : jalon à venir (date_prevue ≥ date du jour) non confirmé depuis plus de 7 jours (vigilance), plus de 14 jours (blocage).',
      'Étiquette de l’échéancier : À REVOIR si non confirmé depuis plus de 14 jours ; sinon EN RETARD si l’écart à la référence est positif ; sinon DANS LES TEMPS.',
      'Jalon hors période : date_prevue avant le début ou après la fin de sa phase (avertissement).',
      DATES_TEXTE,
      'Droits : un jalon sans chantier_id est visible de tout le projet ; sinon, règle des chantiers (PMO : tout ; Responsable / Lecteur : ses chantiers).',
    ],
  },
  {
    nom: 'livrables',
    source: '"Deliverable" t',
    description: 'Livrables du projet : sous-phase, chantier, échéance, avancement et risque (maîtrisé, sous tension, critique). Écran : Pilotage › Livrables.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du livrable' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom du livrable' },
      { nom: 'sous_phase_id', expr: `t.${q('subphaseId')}`, type: 'texte', signification: 'Sous-phase → sous_phases.id' },
      { nom: 'chantier_id', expr: `t.${q('workstreamId')}`, type: 'texte', signification: 'Chantier → chantiers.id (facultatif)' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Responsable → personnes.id' },
      { nom: 'date_debut', expr: 't.start', type: 'texte', signification: 'Début (null : début de la sous-phase)', exemples: 'AAAA-MM-JJ' },
      { nom: 'echeance', expr: 't.due', type: 'texte', signification: 'Échéance', exemples: 'AAAA-MM-JJ' },
      { nom: 'avancement_pct', expr: 't.prog', type: 'entier', signification: 'Avancement', exemples: 'en %' },
      { nom: 'risque_force', expr: `t.${q('riskOverride')}::text`, type: 'texte', signification: 'Risque saisi à la main (null : calculé)', exemples: 'OK = maîtrisé, TENSION = sous tension, CRITICAL = critique' },
      { nom: 'equipe', expr: `t.${q('teamLabel')}`, type: 'texte', signification: 'Équipe réalisatrice (libellé)' },
    ],
    relations: ['livrables.sous_phase_id = sous_phases.id', 'livrables.chantier_id = chantiers.id'],
    usages: ['Livrables en retard ou critiques.', 'Livrables à échéance dans les 30 jours.', 'Taux de livrables terminés.'],
    regles: [
      'Dates effectives : début = COALESCE(date_debut, début de la sous-phase) ; échéance = COALESCE(echeance, fin de la sous-phase, début + 120 jours).',
      'Statut : terminé si avancement_pct ≥ 100 ; en retard si date du jour > échéance ; actif si (début renseigné et date du jour ≥ début) ou avancement_pct > 0 ; à venir sinon.',
      'Risque = risque_force s’il est renseigné ; sinon : en retard → critique ; statut autre qu’actif → maîtrisé ; actif : écoulé = clamp((date du jour − début) / max(1, échéance − début), 0, 1), écart = écoulé × 100 − avancement_pct ; critique si écart > 18, sous tension si écart > 6, maîtrisé sinon.',
      'À échéance dans les 30 jours = non terminé et date du jour ≤ échéance ≤ date du jour + 30. Taux terminé = round(terminés / total × 100).',
      DATES_TEXTE,
      'Droits : les livrables sont visibles de tout le projet (pas de filtre par chantier dans le Cockpit).',
    ],
  },
  {
    nom: 'equipes',
    source: '"Team" t',
    description: 'Équipes du projet (client, AMOA, intégrateur…).',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant de l’équipe' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom de l’équipe' },
      { nom: 'description', expr: 't.description', type: 'texte', signification: 'Description' },
      { nom: 'type', expr: 't.kind::text', type: 'texte', signification: 'Organisation', exemples: 'CLIENT, AMOA, INTEGRATOR = intégrateur, OTHER = autre' },
    ],
    relations: ['equipes.id = personnes.equipe_id'],
    usages: ['Effectif par équipe.'],
    regles: ['Effectif d’une équipe = nombre de personnes actives de l’équipe.', DROITS_PROJET],
  },
  {
    nom: 'roles',
    source: '"ProjectRole" t',
    description: 'Rôles du projet (organigramme) : libellé et niveau.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du rôle' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'libelle', expr: 't.label', type: 'texte', signification: 'Libellé du rôle', exemples: 'Chef de projet, PMO' },
      { nom: 'description', expr: 't.description', type: 'texte', signification: 'Description' },
      { nom: 'niveau', expr: 't.tier', type: 'entier', signification: 'Niveau dans l’organigramme', exemples: '0 (direction) à 3' },
    ],
    relations: ['roles.id = affectations.role_id'],
    usages: ['Qui occupe tel rôle ?'],
    regles: ['Effectif d’un rôle = personnes actives distinctes ayant une affectation active sur ce rôle.', DROITS_PROJET],
  },
  {
    nom: 'personnes',
    source: '"Person" t',
    description: 'Personnes de l’équipe projet (Référentiel) : identité, équipe, fonction. Une ligne par personne et par projet.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant de la personne (= responsable_id, decideur_id… des autres vues)' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'prenom', expr: `t.${q('firstName')}`, type: 'texte', signification: 'Prénom' },
      { nom: 'nom', expr: `t.${q('lastName')}`, type: 'texte', signification: 'Nom de famille' },
      { nom: 'email', expr: 't.email', type: 'texte', signification: 'Adresse e-mail (unique dans le projet)' },
      { nom: 'equipe_id', expr: `t.${q('teamId')}`, type: 'texte', signification: 'Équipe → equipes.id' },
      { nom: 'fonction', expr: 't.title', type: 'texte', signification: 'Fonction dans le projet' },
      { nom: 'active', expr: 't.active', type: 'booléen', signification: 'Personne active dans le projet' },
      { nom: 'chantiers_affiches', expr: `t.${q('wsIds')}`, type: 'liste de textes', signification: 'Chantiers de rattachement affichés (ne donnent aucun droit)' },
    ],
    relations: ['personnes.id = responsable_id, decideur_id, approuvee_par_id, relecteur_id, valideur_id… des autres vues', 'personnes.equipe_id = equipes.id'],
    usages: ['Nom d’un responsable (joindre sur responsable_id).', 'Charge par personne : actions, risques ouverts.'],
    regles: [
      'Afficher « prénom nom » plutôt que l’identifiant ; joindre sur le même projet_id.',
      'Porteur sans affectation active = personne sans affectation active qui porte au moins un objet ouvert (jalon à venir, action non terminée, risque non clos, problème non résolu, décision en cours, livrable < 100 %, chantier actif).',
      DROITS_PROJET,
    ],
  },
  {
    nom: 'affectations',
    source: '"Assignment" t',
    description: 'Affectations des personnes aux rôles du projet, avec leurs dates.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'personne_id', expr: `t.${q('personId')}`, type: 'texte', signification: 'Personne → personnes.id' },
      { nom: 'role_id', expr: `t.${q('roleId')}`, type: 'texte', signification: 'Rôle → roles.id' },
      { nom: 'date_debut', expr: `t.${q('startDate')}`, type: 'texte', signification: 'Date de début', exemples: 'AAAA-MM-JJ' },
      { nom: 'date_fin', expr: `t.${q('endDate')}`, type: 'texte', signification: 'Fin (null : sans fin)', exemples: 'AAAA-MM-JJ' },
    ],
    relations: ['affectations.personne_id = personnes.id', 'affectations.role_id = roles.id'],
    usages: ['Qui est affecté à quel rôle aujourd’hui ?', 'Affectations sans date de fin.'],
    regles: [
      'Affectation active = date_debut ≤ date du jour et (date_fin null ou date_fin ≥ date du jour).',
      '« Fin manquante » : date_fin null pour une personne d’une équipe qui n’est pas CLIENT.',
      DATES_TEXTE,
      DROITS_PROJET,
    ],
  },
  {
    nom: 'instances',
    source: '"GovernanceBody" t',
    description: 'Instances de gouvernance (COPIL, COPROJ…) : niveau, fréquence.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant de l’instance', exemples: 'g1' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom de l’instance', exemples: 'Comité de pilotage' },
      { nom: 'sigle', expr: `t.${q('shortName')}`, type: 'texte', signification: 'Sigle', exemples: 'COPIL, COPROJ' },
      { nom: 'frequence', expr: 't.frequency::text', type: 'texte', signification: 'Fréquence', exemples: 'DAILY = quotidienne, WEEKLY = hebdomadaire, BIWEEKLY = bimensuelle, MONTHLY = mensuelle, QUARTERLY = trimestrielle, SEMIANNUAL = semestrielle, ON_DEMAND = à la demande' },
      { nom: 'niveau', expr: 't.level::text', type: 'texte', signification: 'Niveau', exemples: 'STRATEGIC = stratégique, STEERING = pilotage, OPERATIONAL = opérationnel, OFF_CYCLE = hors cycle' },
      { nom: 'description', expr: 't.description', type: 'texte', signification: 'Description' },
    ],
    relations: ['instances.id = seances.instance_id, decisions.instance_id, membres_instances.instance_id'],
    usages: ['Quelles instances, à quelle fréquence ?'],
    regles: [DROITS_PROJET],
  },
  {
    nom: 'membres_instances',
    source: '"BodyMember" t JOIN "GovernanceBody" b ON b.id = t."bodyId"',
    description: 'Membres de chaque instance et leur rôle.',
    colonnes: [
      { nom: 'projet_id', expr: 'b."projectId"', type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'instance_id', expr: `t.${q('bodyId')}`, type: 'texte', signification: 'Instance → instances.id' },
      { nom: 'personne_id', expr: `t.${q('personId')}`, type: 'texte', signification: 'Membre → personnes.id' },
      { nom: 'role', expr: 't.role::text', type: 'texte', signification: 'Rôle dans l’instance', exemples: 'CHAIR = président, MEMBER = membre, SECRETARY = secrétaire, GUEST = invité' },
    ],
    relations: ['membres_instances.instance_id = instances.id', 'membres_instances.personne_id = personnes.id'],
    usages: ['Qui siège au COPIL ?'],
    regles: [DROITS_PROJET],
  },

  // ───────────── Transactionnel ─────────────
  {
    nom: 'risques',
    source: '"Risk" t',
    description: 'Registre des risques : probabilité, impact, criticité, plan de mitigation, porteur, chantier. Écran : Pilotage › Risques.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code', exemples: 'R01, R05' },
      { nom: 'libelle', expr: 't.n', type: 'texte', signification: 'Libellé du risque' },
      { nom: 'probabilite', expr: 't.p', type: 'entier', signification: 'Probabilité', exemples: '1 à 5' },
      { nom: 'impact', expr: 't.i', type: 'entier', signification: 'Impact', exemples: '1 à 5' },
      { nom: 'criticite', expr: 't.p * t.i', type: 'entier', signification: 'Criticité = probabilité × impact', exemples: '1 à 25' },
      { nom: 'plan_mitigation', expr: 't.plan', type: 'texte', signification: 'Plan de mitigation (null ou vide : aucun)' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Porteur → personnes.id' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier → chantiers.id' },
      { nom: 'echeance', expr: `t.${q('dueIso')}`, type: 'texte', signification: 'Échéance', exemples: 'AAAA-MM-JJ' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'OPEN = ouvert, MITIGATING = en mitigation, CLOSED = clos' },
    ],
    relations: ['risques.chantier_id = chantiers.id', 'risques.responsable_id = personnes.id', 'risques.id = problemes.risque_origine_id'],
    usages: ['Risques critiques ouverts.', 'Risques critiques sans plan de mitigation.', 'Matrice probabilité × impact.'],
    regles: [
      'Niveau : critique si criticite ≥ 20 ; élevé si ≥ 12 ; modéré si ≥ 6 ; faible sinon.',
      'Risque ouvert = statut autre que CLOSED.',
      'Anomalie bloquante « risque critique sans plan » : ouvert, criticite ≥ 20 et plan_mitigation null ou vide.',
      DROITS_CHANTIER,
    ],
  },
  {
    nom: 'problemes',
    source: '"Issue" t',
    description: 'Problèmes (risques avérés) : gravité, porteur, chantier, date cible de résolution.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code', exemples: 'P01' },
      { nom: 'libelle', expr: 't.n', type: 'texte', signification: 'Libellé du problème' },
      { nom: 'gravite', expr: 't.sev', type: 'entier', signification: 'Gravité', exemples: '1 à 5' },
      { nom: 'risque_origine_id', expr: `t.${q('originRiskId')}`, type: 'texte', signification: 'Risque d’origine → risques.id' },
      { nom: 'ouvert_le', expr: `t.${q('openedIso')}`, type: 'texte', signification: 'Date d’ouverture', exemples: 'AAAA-MM-JJ' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Porteur → personnes.id' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier → chantiers.id' },
      { nom: 'date_cible', expr: `t.${q('targetIso')}`, type: 'texte', signification: 'Date cible de résolution (celle de la séance cible si elle est renseignée)', exemples: 'AAAA-MM-JJ' },
      { nom: 'seance_cible_id', expr: `t.${q('targetSessionId')}`, type: 'texte', signification: 'Séance cible → seances.id' },
      { nom: 'detail', expr: 't.detail', type: 'texte', signification: 'Détail' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'OPEN = ouvert, RESOLVING = en résolution, RESOLVED = résolu' },
    ],
    relations: ['problemes.chantier_id = chantiers.id', 'problemes.risque_origine_id = risques.id', 'problemes.seance_cible_id = seances.id'],
    usages: ['Problèmes ouverts par gravité.', 'Problèmes dont la date cible est dépassée.'],
    regles: ['Problème ouvert = statut autre que RESOLVED.', DATES_TEXTE, DROITS_CHANTIER],
  },
  {
    nom: 'actions',
    source: '"Action" t',
    description: 'Plan d’actions : porteur, chantier, échéance, statut, priorité, origine. Écrans : Pilotage › Actions, Aujourd’hui (mes tâches).',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code', exemples: 'A-01, A-45' },
      { nom: 'libelle', expr: 't.n', type: 'texte', signification: 'Libellé de l’action' },
      { nom: 'detail', expr: 't.detail', type: 'texte', signification: 'Détail' },
      { nom: 'responsable_id', expr: `t.${q('ownerId')}`, type: 'texte', signification: 'Porteur → personnes.id' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier → chantiers.id' },
      { nom: 'echeance', expr: `t.${q('dueIso')}`, type: 'texte', signification: 'Échéance (null : sans échéance)', exemples: 'AAAA-MM-JJ' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'OPEN = à faire, IN_PROGRESS = en cours, BLOCKED = bloquée, DONE = terminée' },
      { nom: 'priorite', expr: 't.prio::text', type: 'texte', signification: 'Priorité', exemples: 'HIGH = haute, MEDIUM = moyenne, LOW = basse' },
      { nom: 'origine_type', expr: `t.${q('sourceType')}::text`, type: 'texte', signification: 'Type de l’objet d’origine', exemples: 'RISK, ISSUE, MILESTONE, DECISION' },
      { nom: 'origine_id', expr: `t.${q('sourceId')}`, type: 'texte', signification: 'Objet d’origine (risques.id, problemes.id, jalons.id ou decisions.id selon origine_type)' },
      { nom: 'terminee_le', expr: `t.${q('closedAt')}`, type: 'texte', signification: 'Date de passage à « terminée » (effacée à la réouverture)', exemples: 'AAAA-MM-JJ' },
    ],
    relations: ['actions.chantier_id = chantiers.id', 'actions.responsable_id = personnes.id'],
    usages: ['Actions en retard, par porteur ou par chantier.', 'Actions de la semaine.', 'Actions bloquées.'],
    regles: [
      'Action en retard = statut ≠ DONE et echeance non null et echeance < date du jour (anomalie bloquante).',
      'Action ouverte = statut ≠ DONE.',
      DATES_TEXTE,
      DROITS_CHANTIER,
    ],
  },
  {
    nom: 'decisions',
    source: '"Decision" t',
    description: 'Registre des décisions : intitulé, statut (brouillon → arbitrée), instance, décideur, séance prévue, décision retenue. Écran : Comités › Décisions.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'code', expr: 't.code', type: 'texte', signification: 'Code', exemples: 'D-001, D-007' },
      { nom: 'intitule', expr: 't.t', type: 'texte', signification: 'Intitulé de la question à trancher' },
      { nom: 'priorite', expr: 't.p', type: 'entier', signification: 'Priorité', exemples: '1 (haute) à 4' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'DRAFT = brouillon, IN_REVIEW = en instruction, TO_ARBITRATE = à arbitrer, ARBITRATED = arbitrée, CANCELLED = annulée, SUPERSEDED = remplacée' },
      { nom: 'creee_le', expr: `t.${q('crIso')}`, type: 'texte', signification: 'Date de création', exemples: 'AAAA-MM-JJ' },
      { nom: 'decidee_le', expr: `t.${q('ddIso')}`, type: 'texte', signification: 'Date de la décision (posée à la clôture)', exemples: 'AAAA-MM-JJ' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier → chantiers.id' },
      { nom: 'instance_id', expr: `t.${q('bodyId')}`, type: 'texte', signification: 'Instance qui arbitre → instances.id' },
      { nom: 'decision', expr: `t.${q('decL')}`, type: 'texte', signification: 'Texte de la décision retenue (obligatoire si arbitrée)' },
      { nom: 'decideur_id', expr: `t.${q('makerId')}`, type: 'texte', signification: 'Décideur → personnes.id' },
      { nom: 'impact', expr: 't.impact', type: 'texte', signification: 'Impact de la décision' },
      { nom: 'remplace_id', expr: `t.${q('supersedesId')}`, type: 'texte', signification: 'Décision remplacée → decisions.id' },
      { nom: 'seance_prevue_id', expr: `t.${q('expectedSessionId')}`, type: 'texte', signification: 'Séance où elle doit être arbitrée → seances.id' },
      { nom: 'fiche_complete', expr: 't.full', type: 'booléen', signification: 'Fiche d’arbitrage complète (options, critères, recommandation)' },
      { nom: 'option_retenue', expr: 't.opt', type: 'texte', signification: 'Option retenue', exemples: 'A, B' },
    ],
    relations: ['decisions.chantier_id = chantiers.id', 'decisions.instance_id = instances.id', 'decisions.seance_prevue_id = seances.id', 'decisions.decideur_id = personnes.id'],
    usages: ['Décisions à arbitrer au prochain COPIL.', 'Décisions prises depuis la dernière séance.', 'Validations en attente d’un décideur.'],
    regles: [
      'Décision en cours = statut DRAFT, IN_REVIEW ou TO_ARBITRATE. Décision close = ARBITRATED, CANCELLED ou SUPERSEDED.',
      'Validations d’une personne (écran Aujourd’hui) = décisions TO_ARBITRATE dont elle est le décideur.',
      DATES_TEXTE,
      DROITS_CHANTIER,
    ],
  },
  {
    nom: 'seances',
    source: '"Session" t',
    description: 'Séances des instances (COPIL n°20…) : date, heure, lieu, statut, participants, rapport. Écran : Comités et rapports.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant de la séance' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'instance_id', expr: `t.${q('bodyId')}`, type: 'texte', signification: 'Instance → instances.id' },
      { nom: 'numero', expr: 't.number', type: 'entier', signification: 'Numéro de la séance dans l’instance', exemples: '20, 21' },
      { nom: 'date', expr: `t.${q('dateIso')}`, type: 'texte', signification: 'Date', exemples: 'AAAA-MM-JJ' },
      { nom: 'heure', expr: 't.time', type: 'texte', signification: 'Heure', exemples: '14:00' },
      { nom: 'lieu', expr: 't.place', type: 'texte', signification: 'Lieu' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'PLANNED = planifiée, HELD = tenue, CANCELLED = annulée' },
      { nom: 'participants', expr: 't.participants', type: 'liste de textes', signification: 'Participants (identifiants → personnes.id)' },
      { nom: 'rapport_id', expr: `t.${q('reportId')}`, type: 'texte', signification: 'Rapport de la séance → rapports.id' },
    ],
    relations: ['seances.instance_id = instances.id', 'seances.rapport_id = rapports.id', 'seances.id = decisions.seance_prevue_id, rapports.seance_id'],
    usages: ['Prochain COPIL.', 'Séances à confirmer.', 'Historique des séances.'],
    regles: [
      'Prochaine séance d’une instance = statut PLANNED et date ≥ date du jour, la plus proche. Le « prochain COPIL » est la prochaine séance de l’instance de sigle COPIL (à défaut, de la première instance de niveau STRATEGIC), triée par date puis heure.',
      'Séance à confirmer = statut PLANNED et date ≤ date du jour.',
      'Libellé : sigle ou nom de l’instance + « n° » + numero.',
      DATES_TEXTE,
      DROITS_PROJET,
    ],
  },
  {
    nom: 'modeles_rapport',
    source: '"ReportTemplate" t',
    description: 'Modèles (templates) de rapport de comité : instance, auteur, version, nombre de pages, publication.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du modèle' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom du modèle' },
      { nom: 'instance_id', expr: `t.${q('bodyId')}`, type: 'texte', signification: 'Instance → instances.id' },
      { nom: 'auteur_id', expr: `t.${q('authorId')}`, type: 'texte', signification: 'Auteur → personnes.id' },
      { nom: 'auteur', expr: `t.${q('authorLabel')}`, type: 'texte', signification: 'Auteur (libellé)' },
      { nom: 'version', expr: 't.version', type: 'texte', signification: 'Version du modèle', exemples: 'v2' },
      { nom: 'description', expr: 't.description', type: 'texte', signification: 'Description' },
      { nom: 'pages', expr: 't.pages', type: 'entier', signification: 'Nombre de pages' },
      { nom: 'publie_le', expr: `t.${q('publishedAt')}`, type: 'texte', signification: 'Date de publication', exemples: 'AAAA-MM-JJ' },
      { nom: 'actif', expr: 't.active', type: 'booléen', signification: 'Modèle actif (utilisable pour générer un rapport)' },
    ],
    relations: ['modeles_rapport.instance_id = instances.id', 'modeles_rapport.id = rapports.modele_id'],
    usages: ['Modèles actifs par instance.'],
    regles: ['Pages = 1 + somme des poids des sections (synthèse 2, planning 3, jalons 2, risques 3, décisions 2, actions 2, baromètre 2, tableau de bord 2, budget 2).', DROITS_PROJET],
  },
  {
    nom: 'rapports',
    source: '"ReportInstance" t',
    description: 'Rapports de comité générés : séance, version, statut (brouillon, relecture, publié), date des données capturées.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du rapport' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'modele_id', expr: `t.${q('templateId')}`, type: 'texte', signification: 'Modèle → modeles_rapport.id' },
      { nom: 'seance_id', expr: `t.${q('sessionId')}`, type: 'texte', signification: 'Séance → seances.id' },
      { nom: 'nom', expr: 't.name', type: 'texte', signification: 'Nom du rapport' },
      { nom: 'version', expr: 't.v', type: 'texte', signification: 'Version', exemples: 'v1, v2' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'DRAFT = brouillon, IN_REVIEW = en relecture, PUBLISHED = publié' },
      { nom: 'genere_le', expr: P(q('generatedAt')), type: 'date-heure', signification: 'Génération (heure de Paris)' },
      { nom: 'date_reporting', expr: `t.${q('reportingDate')}`, type: 'texte', signification: 'Date de reporting', exemples: 'AAAA-MM-JJ' },
      { nom: 'capture_le', expr: P(q('captureAt')), type: 'date-heure', signification: 'Capture des données du rapport (heure de Paris)' },
      { nom: 'relecteur_id', expr: `t.${q('reviewerId')}`, type: 'texte', signification: 'Relecteur → personnes.id' },
      { nom: 'valideur_id', expr: `t.${q('validatorId')}`, type: 'texte', signification: 'Valideur → personnes.id' },
      { nom: 'destinataires', expr: 't.audience', type: 'texte', signification: 'Destinataires' },
    ],
    relations: ['rapports.seance_id = seances.id', 'rapports.modele_id = modeles_rapport.id'],
    usages: ['Le support du prochain comité est-il prêt ?', 'Rapports en relecture.'],
    regles: ['Anomalie « changements depuis la capture » : objets modifiés (journal) après capture_le du dernier rapport.', DROITS_PROJET],
  },
  {
    nom: 'barometre_releves',
    source: '"BarometerSurvey" t',
    description: 'Relevés mensuels du baromètre des équipes : note globale, répondants, sentiment, thèmes.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'mois', expr: 't.month', type: 'texte', signification: 'Mois du relevé', exemples: 'AAAA-MM' },
      { nom: 'note_globale', expr: `t.${q('overallScore')}`, type: 'décimal', signification: 'Note globale', exemples: 'sur 10, 1 décimale' },
      { nom: 'repondants', expr: 't.respondents', type: 'entier', signification: 'Nombre de répondants' },
      { nom: 'sentiment_positif_pct', expr: `(t.sentiment->>'positive')::float`, type: 'décimal', signification: 'Part de sentiment positif', exemples: 'en % (les trois parts font 100)' },
      { nom: 'sentiment_neutre_pct', expr: `(t.sentiment->>'neutral')::float`, type: 'décimal', signification: 'Part de sentiment neutre', exemples: 'en %' },
      { nom: 'sentiment_negatif_pct', expr: `(t.sentiment->>'negative')::float`, type: 'décimal', signification: 'Part de sentiment négatif', exemples: 'en %' },
      { nom: 'themes', expr: 't.themes', type: 'json', signification: 'Thèmes du relevé et leur tendance' },
    ],
    relations: ['barometre_releves.projet_id = projets.id'],
    usages: ['Évolution de la note globale.', 'Sentiment du dernier relevé.'],
    regles: ['Dernier relevé = mois le plus récent.', 'Saisie réservée au chantier C8 ; lecture : tout le projet.', DROITS_PROJET],
  },
  {
    nom: 'barometre_domaines',
    source: '"BarometerDomain" t',
    description: 'Domaines du baromètre : effectif, répondants, notes par mois.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'domaine', expr: 't.n', type: 'texte', signification: 'Nom du domaine' },
      { nom: 'effectif', expr: 't.size', type: 'entier', signification: 'Effectif du domaine' },
      { nom: 'repondants', expr: 't.resp', type: 'entier', signification: 'Répondants' },
      { nom: 'plage', expr: 't.range', type: 'texte', signification: 'Plage de la dernière note' },
      { nom: 'notes_par_mois', expr: 't.series', type: 'json', signification: 'Notes par mois', exemples: '{"2026-08": 6.1, "2026-09": null}' },
    ],
    relations: ['barometre_domaines.projet_id = projets.id'],
    usages: ['Domaines en baisse.'],
    regles: ['Lire une note : (notes_par_mois->>\'AAAA-MM\')::float ; null = pas de note ce mois.', DROITS_PROJET],
  },
  {
    nom: 'mission',
    source: '"MissionPeriod" t',
    description: 'Périodes de la mission (budget) : montants AMOA et sous-traitance, statut de facturation. Module Budget.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'periode', expr: 't.period', type: 'texte', signification: 'Période (libellé libre, pas une date)' },
      { nom: 'montant_amoa', expr: 't.amoa', type: 'décimal', signification: 'Montant AMOA', exemples: 'dans la devise du projet' },
      { nom: 'montant_sous_traitance', expr: 't.sub', type: 'décimal', signification: 'Montant de sous-traitance', exemples: 'dans la devise du projet' },
      { nom: 'total', expr: 't.amoa + t.sub', type: 'décimal', signification: 'Total de la période = AMOA + sous-traitance' },
      { nom: 'statut', expr: 't.status::text', type: 'texte', signification: 'Statut', exemples: 'INVOICED = facturé, IN_PROGRESS = en cours, NEGOTIATION = en négociation' },
    ],
    relations: ['mission.projet_id = projets.id'],
    usages: ['Montant facturé, en cours, en négociation.'],
    regles: ['Visible seulement si le module Budget est actif pour le projet.', DROITS_PROJET],
  },
  {
    nom: 'budget_programme',
    source: '"ProgramBudget" t',
    description: 'Budget du programme : connu ou non, et pourquoi.',
    colonnes: [
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'connu', expr: 't.known', type: 'booléen', signification: 'Budget du programme renseigné' },
      { nom: 'motif', expr: 't.reason', type: 'texte', signification: 'Motif si le budget n’est pas connu' },
    ],
    relations: ['budget_programme.projet_id = projets.id'],
    usages: ['Le budget est-il connu ?'],
    regles: ['Anomalie « budget non renseigné » : connu faux.', DROITS_PROJET],
  },
  {
    nom: 'documents',
    source: '"Document" t',
    description: 'Base de connaissance : documents du projet (type, version, confidentialité, état de l’extraction).',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant du document' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'nom', expr: 't.n', type: 'texte', signification: 'Titre du document' },
      { nom: 'type', expr: 't.type', type: 'texte', signification: 'Type', exemples: 'Compte rendu, Livrable, Support de comité, Contractuel' },
      { nom: 'date', expr: `t.${q('dateIso')}`, type: 'texte', signification: 'Date du document', exemples: 'AAAA-MM-JJ' },
      { nom: 'version', expr: 't.v', type: 'texte', signification: 'Version', exemples: 'v1, v2' },
      { nom: 'confidentialite', expr: 't.conf::text', type: 'texte', signification: 'Confidentialité', exemples: 'INTERNAL = interne, RESTRICTED = restreint' },
      { nom: 'origine', expr: 't.src::text', type: 'texte', signification: 'Origine', exemples: 'UPLOADED = déposé, GENERATED = généré' },
      { nom: 'extraction', expr: 't.ext::text', type: 'texte', signification: 'État de l’extraction du texte', exemples: 'PENDING = en attente, SUCCEEDED = extrait et indexé, PARTIAL = partiel, UNSUPPORTED = non exploitable' },
      { nom: 'pages', expr: 't.pages', type: 'entier', signification: 'Nombre de pages' },
      { nom: 'taille_octets', expr: `t.${q('sizeBytes')}`, type: 'entier', signification: 'Taille', exemples: 'en octets' },
      { nom: 'objets_lies', expr: `t.${q('linkedLabel')}`, type: 'texte', signification: 'Objets liés (libellé)' },
    ],
    relations: ['documents.id = liens_documents.document_id'],
    usages: ['Derniers documents déposés.', 'Documents d’une séance ou d’un risque (via liens_documents).'],
    regles: ['Droits : visible de tout le projet, sauf confidentialite = RESTRICTED, réservé au PMO et à l’administrateur.', DATES_TEXTE],
  },
  {
    nom: 'liens_documents',
    source: '"DocumentLink" t JOIN "Document" d ON d.id = t."documentId"',
    description: 'Liens entre documents et objets du projet (risque, action, décision, jalon, livrable, séance, rapport…).',
    colonnes: [
      { nom: 'projet_id', expr: 'd."projectId"', type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'document_id', expr: `t.${q('documentId')}`, type: 'texte', signification: 'Document → documents.id' },
      { nom: 'type_objet', expr: `t.${q('entityType')}`, type: 'texte', signification: 'Type d’objet lié', exemples: 'RISK, ISSUE, ACTION, DECISION, MILESTONE, DELIVERABLE, SESSION, REPORT, PROJECT, WORKSTREAM' },
      { nom: 'objet_id', expr: `t.${q('entityId')}`, type: 'texte', signification: 'Identifiant de l’objet lié (dans la vue de son type)' },
    ],
    relations: ['liens_documents.document_id = documents.id', 'liens_documents.objet_id = risques.id, actions.id, decisions.id, jalons.id, livrables.id, seances.id, rapports.id… selon type_objet'],
    usages: ['Documents liés à un objet.'],
    regles: ['Droits : même règle que le document lié (visible de tout le projet, sauf document RESTRICTED : PMO et administrateur).'],
  },
  {
    nom: 'commentaires',
    source: '"CellComment" t',
    description: 'Commentaires posés sur les objets du Cockpit (collaboration) : texte, auteur, résolu ou non.',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'type_objet', expr: `t.${q('entityType')}`, type: 'texte', signification: 'Type d’objet commenté' },
      { nom: 'objet_id', expr: `t.${q('entityId')}`, type: 'texte', signification: 'Objet commenté' },
      { nom: 'texte', expr: 't.text', type: 'texte', signification: 'Texte du commentaire' },
      { nom: 'auteur_id', expr: `t.${q('authorId')}`, type: 'texte', signification: 'Auteur (personne ou compte)' },
      { nom: 'auteur', expr: `t.${q('authorName')}`, type: 'texte', signification: 'Nom de l’auteur' },
      { nom: 'resolu', expr: 't.resolved', type: 'booléen', signification: 'Commentaire résolu' },
      { nom: 'cree_le', expr: P(q('createdAt')), type: 'date-heure', signification: 'Date du commentaire (heure de Paris)' },
    ],
    relations: ['commentaires.objet_id = identifiant de l’objet selon type_objet'],
    usages: ['Commentaires non résolus.'],
    regles: ['Droits : lisible seulement si l’objet commenté l’est (règle de son chantier).'],
  },
  {
    nom: 'habilitations',
    source: '"Habilitation" t',
    description: 'Droits sur le projet : PMO (tout le projet), Responsable ou Lecteur (un chantier).',
    colonnes: [
      { nom: 'id', expr: 't.id', type: 'texte', signification: 'Identifiant' },
      { nom: 'projet_id', expr: `t.${q('projectId')}`, type: 'texte', signification: 'Projet → projets.id' },
      { nom: 'personne_id', expr: `t.${q('personId')}`, type: 'texte', signification: 'Personne → personnes.id' },
      { nom: 'compte_id', expr: `t.${q('accountId')}`, type: 'texte', signification: 'Compte de connexion (si rattaché au compte)' },
      { nom: 'profil', expr: 't.profile::text', type: 'texte', signification: 'Profil', exemples: 'PMO, RESPONSABLE, LECTEUR' },
      { nom: 'chantier_id', expr: `t.${q('wsId')}`, type: 'texte', signification: 'Chantier (Responsable, Lecteur) → chantiers.id ; null pour PMO' },
    ],
    relations: ['habilitations.personne_id = personnes.id', 'habilitations.chantier_id = chantiers.id'],
    usages: ['Qui est responsable de tel chantier ?', 'Qui peut voir tel chantier ?'],
    regles: ['Profil affiché = le plus fort : PMO > RESPONSABLE > LECTEUR. Le directeur de programme du projet a aussi accès.', DROITS_PROJET],
  },
];

/**
 * Filtre de droits d'une vue, appliqué au seul rôle `jev_lecteur_cockpit` (le compte de l'application voit tout) :
 * projet = `rise.projet` ; lignes d'un chantier : `rise.chantiers` = « * » (PMO, administrateur) ou chantier de la
 * liste ; sans chantier (null) : réservé à « * » (comme `canReadWs`). Exceptions tirées des fiches : livrables
 * visibles de tout le projet ; documents RESTRICTED et commentaires réservés à « * ». Paramètre absent : rien.
 */
export function cockpitRightsFilter(t: DictTable): string {
  const col = (n: string) => t.colonnes.find((c) => c.nom === n)?.expr;
  const all = `current_setting('${SCOPE_CHANTIERS}', true) = '*'`;
  const inList = (e: string) => `(${all} OR ${e} = ANY(string_to_array(current_setting('${SCOPE_CHANTIERS}', true), ',')))`;
  const proj = t.nom === 'projets' ? col('id')! : col('projet_id')!;
  const cond = [`${proj} = current_setting('${SCOPE_PROJET}', true)`];
  if (t.nom === 'chantiers') cond.push(inList(col('id')!));
  else if (t.nom === 'documents') cond.push(`(${all} OR t.conf::text <> 'RESTRICTED')`);
  else if (t.nom === 'liens_documents') cond.push(`(${all} OR d.conf::text <> 'RESTRICTED')`);
  else if (t.nom === 'commentaires') cond.push(all);
  else if (t.nom !== 'livrables' && col('chantier_id')) cond.push(inList(col('chantier_id')!));
  return `(current_user <> '${JEV_COCKPIT_ROLE}' OR (${cond.join(' AND ')}))`;
}

/** Vue du Cockpit avec son filtre de droits (migration `…_jev_cockpit_droits`). */
export function cockpitViewSql(t: DictTable): string {
  const cols = t.colonnes.map((c) => `  ${c.expr} AS ${c.nom}`).join(',\n');
  const where = [t.filtre, cockpitRightsFilter(t)].filter(Boolean).join(' AND ');
  return `CREATE OR REPLACE VIEW ${JEV_COCKPIT_SCHEMA}.${t.nom} AS\nSELECT\n${cols}\nFROM ${t.source}\nWHERE ${where};`;
}
